INFLUX_URL    = "YOUR_INFLUX_URL"
INFLUX_TOKEN  = "YOUR_INFLUX_TOKEN"
INFLUX_ORG    = "whityhat0508@gmail.com"
INFLUX_BUCKET = "YOUR_BUCKET_NAME"
BROKER        = "broker.emqx.io"
PORT          = 8083
