INFLUX_URL    = "https://us-east-1-1.aws.cloud2.influxdata.com"
INFLUX_TOKEN  = "hHQXzVgxsqOIQLS96rFSkOXWqNj_LteErk2kGZ_48uqKgJXDYT1lPf0u_rYQ8lgsb8CBJSnHs1IvI8Caf4CEBw=="
INFLUX_ORG    = "whityhat0508@gmail.com"
INFLUX_BUCKET = "smart-bin-chennai"
BROKER        = "broker.emqx.io"
PORT          = 8083
